"""create_housing_department_records

Revision ID: eb2742421bfb
Revises: 0004_dashboard_manual_summary
Create Date: 2026-05-17 23:51:14.321629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb2742421bfb'
down_revision: Union[str, None] = '0004_dashboard_manual_summary'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('housing_department_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('residential_complex_name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('fio', sa.String(length=255), nullable=True),
    sa.Column('family_composition', sa.Text(), nullable=True),
    sa.Column('initial_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('market_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('reimbursement_cost_monthly', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taxable_base', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('residence_period', sa.String(length=255), nullable=True),
    sa.Column('room_count', sa.Integer(), nullable=True),
    sa.Column('total_area', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('build_year', sa.Integer(), nullable=True),
    sa.Column('personal_account', sa.String(length=128), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('occupancy_and_purchase_basis', sa.Text(), nullable=True),
    sa.Column('rental_contract', sa.String(length=512), nullable=True),
    sa.Column('purchase_contract', sa.String(length=512), nullable=True),
    sa.Column('payment_schedule', sa.String(length=512), nullable=True),
    sa.Column('ownership_document', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_housing_department_records_fio'), 'housing_department_records', ['fio'], unique=False)
    op.create_index(op.f('ix_housing_department_records_residential_complex_name'), 'housing_department_records', ['residential_complex_name'], unique=False)
    op.drop_constraint('dashboard_manual_summary_residential_complex_name_key', 'dashboard_manual_summary', type_='unique')
    op.create_index(op.f('ix_dashboard_manual_summary_residential_complex_name'), 'dashboard_manual_summary', ['residential_complex_name'], unique=True)
    op.drop_constraint('uq_documents_document_group_key_version_no', 'documents', type_='unique')
    op.drop_index('uq_documents_group_current', table_name='documents', postgresql_where='(is_current = true)')
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.drop_index('ix_roles_name', table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index('ix_roles_name', 'roles', ['name'], unique=False)
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.create_index('uq_documents_group_current', 'documents', ['document_group_key'], unique=True, postgresql_where='(is_current = true)')
    op.create_unique_constraint('uq_documents_document_group_key_version_no', 'documents', ['document_group_key', 'version_no'])
    op.drop_index(op.f('ix_dashboard_manual_summary_residential_complex_name'), table_name='dashboard_manual_summary')
    op.create_unique_constraint('dashboard_manual_summary_residential_complex_name_key', 'dashboard_manual_summary', ['residential_complex_name'])
    op.drop_index(op.f('ix_housing_department_records_residential_complex_name'), table_name='housing_department_records')
    op.drop_index(op.f('ix_housing_department_records_fio'), table_name='housing_department_records')
    op.drop_table('housing_department_records')
    # ### end Alembic commands ###
