/**
 * Budget Rent table columns — order and labels match Excel sheet "2026 Март".
 * field must match budget_rent_records / API response keys.
 */
export const BUDGET_RENT_COLUMNS = [
  { field: "valuation_object", label: "Объект оценки", type: "text", sticky: 1 },
  { field: "residential_complex_name", label: "Наименование ЖК", type: "text", sticky: 2 },
  { field: "street", label: "Улица", type: "text" },
  { field: "house_number", label: "Дом", type: "text" },
  { field: "apartment_number", label: "Квартира", type: "text" },
  { field: "address", label: "Адрес", type: "text", wide: true },
  { field: "quantity", label: "Количество", type: "num" },
  { field: "market_price", label: "Рыночная цена", type: "num" },
  {
    field: "proportional_market_price",
    label: "Рыночная цена деленая пропорционально на количество оформленных договоров",
    type: "num",
    wide: true,
  },
  { field: "balance_value_2025", label: "Балансовая стоимость на 31 декабря 2025 года", type: "num", wide: true },
  {
    field: "proportional_balance_value_2025",
    label: "Балансовая стоимость на 31 декабря 2025 года деленая пропорционально на количество оформленных договоров",
    type: "num",
    wide: true,
  },
  { field: "room_count", label: "Количество комнат", type: "int" },
  { field: "total_area", label: "Общая площадь", type: "num" },
  { field: "living_area", label: "Жилая площадь", type: "num" },
  { field: "occupied_area_sp", label: "Занимаемая площадь в квартире при СП", type: "num", wide: true },
  {
    field: "shared_area_sp_total",
    label: "Общая площадь в СП квартирах (которая делится на всех проживающих пропорционально)",
    type: "num",
    wide: true,
  },
  { field: "shared_area_per_person", label: "Общая площадь в СП квартирах на каждого проживающего", type: "num", wide: true },
  { field: "calculation_area_total", label: "ИТОГО площадь к расчету", type: "num" },
  { field: "fio", label: "ФИО проживающих", type: "text", wide: true },
  { field: "cohabitation", label: "Совместное проживание", type: "text" },
  { field: "cohabitant_count", label: "Количество совместно проживающих", type: "int" },
  { field: "note", label: "Примечание", type: "text", wide: true },
  {
    field: "land_tax_zone_adjustment",
    label: "Корректировка базовых ставок земельного налога с.510 НКРК (зона)",
    type: "num",
    wide: true,
  },
  { field: "astana_land_tax_base_rate", label: "Базовая ставка земельного налога г. Астана, ст.505 НК РК", type: "num", wide: true },
  {
    field: "land_tax_adjustment_for_calc",
    label: "Корректировка базовых ставок земельного налога для расчета",
    type: "num",
    wide: true,
  },
  { field: "correction_coefficient", label: "Кооректировочный коэффициент", type: "num" },
  { field: "land_tax_rate", label: "Ставка земельного налога", type: "num" },
  { field: "land_tax_yearly", label: "Земельный налог в год", type: "num" },
  {
    field: "land_tax_year_ownership_adjustment",
    label: "Земельный налог в год с учетом принятия во владения (сент.–дек.)",
    type: "num",
    wide: true,
  },
  { field: "amortization_monthly", label: "Амортизация в месяц", type: "num" },
  { field: "balance_value_month_1_2026", label: "Балансовая стоимость 1 месяц 2026", type: "num" },
  { field: "balance_value_month_2_2026", label: "Балансовая стоимость 2 месяц 2026", type: "num" },
  { field: "balance_value_month_3_2026", label: "Балансовая стоимость 3 месяц 2026", type: "num" },
  { field: "balance_value_month_4_2026", label: "Балансовая стоимость 4 месяц 2026", type: "num" },
  { field: "balance_value_month_5_2026", label: "Балансовая стоимость 5 месяц 2026", type: "num" },
  { field: "balance_value_month_6_2026", label: "Балансовая стоимость 6 месяц 2026", type: "num" },
  { field: "balance_value_month_7_2026", label: "Балансовая стоимость 7 месяц 2026", type: "num" },
  { field: "balance_value_month_8_2026", label: "Балансовая стоимость 8 месяц 2026", type: "num" },
  { field: "balance_value_month_9_2026", label: "Балансовая стоимость 9 месяц 2026", type: "num" },
  { field: "balance_value_month_10_2026", label: "Балансовая стоимость 10 месяц 2026", type: "num" },
  { field: "balance_value_month_11_2026", label: "Балансовая стоимость 11 месяц 2026", type: "num" },
  { field: "balance_value_month_12_2026", label: "Балансовая стоимость 12 месяц 2026", type: "num" },
  { field: "balance_value_month_13", label: "Балансовая стоимость 13 месяц", type: "num" },
  { field: "property_tax_year_2026", label: "Имущественный налог в год 2026", type: "num" },
  { field: "total_land_and_property_tax_2026", label: "Земельный налог+имущественный налог в год 2026", type: "num", wide: true },
  { field: "material_benefit", label: "Материальная выгода (амортизация в месяц)", type: "num", wide: true },
  {
    field: "reimbursement_cost_monthly",
    label: "Себестоимость сумма возмещения в месяц удержание из ЗП на 2026 год",
    type: "num",
    wide: true,
  },
  { field: "taxable_base", label: "Налогооблагаемая база", type: "num" },
  { field: "contract_status", label: "СТАТУС ДОГОВОРА", type: "text" },
  { field: "rental_contract_number_date", label: "Договор найма жилья номер дата", type: "text", wide: true },
  { field: "attachment_note", label: "Приложение", type: "text", wide: true },
  { field: "changes_note", label: "Изменения", type: "text", wide: true },
];
